### PR TITLE
Update from Upstream

### PR DESCRIPTION
**Pull request by Zeitsperre**
@huard 

I'm thinking that it would be good to start working more closely off the master from Bird-House. As it stands currently, our branch of master is +450 commits behind and rather than push to our Master branch, we've been working as follows:

new_feature_branch --> pavics_dev --> pavics

Assuming that there are no hard-coded server addresses within this repo, wouldn't it make more sense to try more often to push back to upstream master?

new_feature_branch --> pavics_dev --> Ouranosinc/master --> BH/master

This would help solve a lot of diverging commit issues and help us stay current on changes/features that come from upstream. I'm wondering why we follow the previous model.

### CODE REVIEW

**Comment by huard** [comment]
That procedure was set in place when we were noobs and did not want to break FP. Now that FP has sandbox status and we have more experience, your suggestion makes a lot of sense. 

Another option is to push new developments to BH, then use pavics and pavics_dev as a subset that we expose to our own users.

**Review by huard — COMMENTED** [review]
I would restrict the processes that are offered by pavics to a subset of FP processes. Not clear to me for example that the EO processes are mature yet. Apart from that, it's good that we merge regularly with upstream, thanks !

**Comment by Zeitsperre** [comment]
That's good to hear. I'm currently working on changes to BH/FP/master from a personal fork, which seems a bit obtuse. 

I agree with the EO functions, given that the features behind them aren't implemented. Would it be possible to suggest creating a transitional 'EO_processes' folder on BH/FP/master that can be ignored so that they don't get integrated into the active functions?

Would we be good to perform the merge after I've opened/merged my PR from Zeitsperre/FP/better_logs into BH/FP/master?

edit: I haven't created this branch yet, but I'll be adding it in the next few hours. Mainly lots of changes to Exception handlings in the processes.

**Comment by huard** [comment]
My suggestion would simply be to comment to unwanted processes in the processes/__init__.py. 

Yep !

**Comment by cehbrecht** [comment]
@Zeitsperre @huard @nilshempelmann 
It's a tedious work to keep flyingpigeon with all its dependencies alive and it is probably hard to sync *all* processes between those diverged forks. But it is good to get our work in sync again :)

I have updated the wiki with "my personal workflow" to handle forks ... not helpful at this stage but just as a note: https://github.com/bird-house/bird-house.github.io/wiki/Development-Guidelines

I have created a new branch [1.2.x](https://github.com/bird-house/flyingpigeon/tree/1.2.x) with the latest of master in birdhouse/flyingpigeon. So, we don't loose the work that is done on the birdhouse FP.

For the sync I would propose to make it as easy for you as you can :) The goal would be to have both forks in sync again if you like to share the pavics processes. You could:

* reset the birdhouse FP to the pavics FP (that is the brutal merge :)
* disable all process in birdhouse FP you don't want or which are note working. Reduce and update the conda dependencies (as suggested by David).

For the more stable processes in FP we can spawn new birds (using cookiecutter) and remove that code from FP.

**Pull request merged**
