### PR TITLE
[WIP] New and Improved Processes

### PR DESCRIPTION
**Pull request by Zeitsperre**
@huard I'd like to try my hand at developing some new algorithms for FP as well as rewrite some of the process descriptions and reoganize their code a bit (checks for PEP8, python 2/3 compatibility, leverage newer/better functions). This is just a proposal but let me know what you think:

- [ ] Refactoring/reorganizing FP processes (PEP8 and clearer comments)
- [ ] Editing the process descriptions and abstracts for clarity
- [ ] Add new FP processes:
    - [ ] Heat Summation Indices (e.g. Degree-Days, Biologically Effective Degree-Days, Corn-Heat-Units)
    - [ ] Plot Probability Density Function (from points/polygons(?))

### CODE REVIEW

**Comment by dbyrns** [comment]
Just keep in mind that this is a forked repo from birdhouse. If you are to change a lot of files make sure that the changes will be approved in a PR else we will not be able to pull latest changes from their side easily.

**Comment by Zeitsperre** [comment]
Would you suggest basing my changes off of the bird-house original code? I can try adding my changes in a PR directly to bird-house/flyingpigeon if that works better.

**Comment by dbyrns** [comment]
Since your modification are not related to PAVICS I think it is the way to go.
I'm not sure though of the flyingpigeon synch state between birdhouse and ouranos branch. So you should check if it will be easy to pull back birdhouse/master commits into our current branch.

**Review by huard — CHANGES_REQUESTED** [review]
Not sure I like the KDDMbiascorrectProcess name, feels too long. Other name changes make sense. 
You'll have to submit that upstream to the birdhouse team as well. They may have other tools that depend on the old names. 
Also, this will certainly affect tests and I see no changes there. 
It might also break some integration testing code on the UI side. 
So my feeling is that there is a lot of breakage potential due to the name changes, for essentially aesthetic reasons. It's not clear to me if it's worth the pain we'll cause ourselves and others. Other pep8 changes are all good. 

My suggestion would be to defer name changes when we'll move processes from their sandbox (FP) to their final destination.

**Comment by Zeitsperre** [comment]
Rolling back the changes and opening a new PR that implements PEP8 but doesn't break naming conventions.

**Comment by huard** [comment]
OK, I suggest you keep your re-naming suggestions as comments in the code so we don't forget to do the renaming when we move the processes.

**Pull request closed without merging**
