### PR TITLE
Refactor FP Processes for PEP8

### PR DESCRIPTION
**Pull request by Zeitsperre**
@huard Here`s another try at fixing some of the PEP8 violations while not breaking process names. Goals are the same as previously.

- [x] Refactoring/reorganizing FP processes (PEP8 and clearer comments)
- [ ] Editing the process descriptions and abstracts for clarity
- [ ] Add new FP processes:
    - [ ] Heat Summation Indices (e.g. Degree-Days, Biologically Effective Degree-Days, Corn-Heat-Units)
    - [ ] Plot Probability Density Function (from points/polygons(?))

### CODE REVIEW

**Review by huard — APPROVED** [review]
looks good

**Comment by huard** [comment]
I guess the next step would be to pull these changes upstream in birdhouse, along with some of the processes we've contributed. This might get hairy, and I suggest you coordinate with Nils who is also doing some refactoring with the integration of eggshell.

**Comment by Zeitsperre** [comment]
@huard Thanks for the advice, I'll try opening a PR on bird-house master for this. One last thing I want to understand/cleanup is the error-handling conventions I've found.

I'm looking at some of the error-handling within the processes and I'm wondering if the following is intentional. One method is to raise a bare exception with a generic statement: 
```
try:
    tarf = archive(results)
    LOGGER.info('Tar file prepared')
except:
    msg = 'Tar file preparation failed'
    LOGGER.exception(msg)
    raise Exception(msg)
```
or
```
except:
     LOGGER.exception('failed to write resources to textfile')
```
From what I understand, this catches any and all exceptions, including exceptions that can arise from other parts of FP. This also hides the actual error (SystemError, FileError, TypeError, etc.). I can see this generic error being useful for client-facing logs, but wouldn't it also make sense to catch the specific error within the log file?

I`ve also come across a few other error handling methods that either append the error to the message:
```
except Exception as e:
    msg = "Failed to create figure: {}".format(e)
    LOGGER.error(msg)
    raise Exception(msg)
```
or raise a portion of the stacktrace to the error (which makes a lot of sense, re: debugging):
```
except:
    raise Exception(traceback.format_exc())
```

For many of these processes, logging is not consistently implemented, which makes me wonder which algorithms we want to log (all of them? only Ouranos-produced ones? only those in development?). There's also the issue of different error-handling methods creating temporary/permanent files (e.g. do we want to erase the ones that are raised on the UI of PAVICS after they are presented?).

I guess my question here is which messages are presented to the user when an `Exception` occurs (`raise`, `LOGGER`) and are the bare `except` clauses that I'm finding intentional or should they be cleaned up?

**Comment by Zeitsperre** [comment]
@dbyrns would you happen to know more about this?

**Pull request merged**
